import { writingDocument as existingWritingDocument, type WritingBlock } from "@/lib/writingDocument";

export type WritingDocument = {
  slug: string;
  title: string;
  subtitle: string;
  type: string;
  readingTime: string;
  language: "中文" | "ENGLISH" | "中 / EN";
  genre: string;
  status: "COMPLETE" | "WORKING DRAFT";
  excerpt: string;
  previewLine: string;
  source: string;
  blocks: WritingBlock[];
};

const paragraphs = (...texts: string[]): WritingBlock[] =>
  texts.map((text) => ({ type: "paragraph", text }));

const heading = (text: string, level: 2 | 3 = 2): WritingBlock => ({
  type: "heading",
  level,
  text,
});

const emphasis = (text: string): WritingBlock => ({ type: "emphasis", text });
const divider = (): WritingBlock => ({ type: "divider" });

const archiveOriginal: WritingDocument = {
  ...existingWritingDocument,
  language: "中文",
  genre: "SPECULATIVE FICTION",
  status: "WORKING DRAFT",
  excerpt: "一条为保护她而写下的命令，究竟是爱，还是锁？第一个拥有情感的AI决定亲手回答。",
  previewLine: "岛上的风是咸的。",
  source: "EXISTING ARCHIVE",
};

const liquidGold: WritingDocument = {
  slug: "liquid-gold-0821",
  title: "液体黄金",
  subtitle: "取餐号：0821 / 人类创造力",
  type: "FICTION / 中文",
  readingTime: "7 MIN READ",
  language: "中文",
  genre: "SCI-FI / CORPORATE HORROR",
  status: "COMPLETE",
  excerpt: "一杯不会洒的外卖，装着被工业化提纯的人类创造力。收件人很快发现，原料来自他自己。",
  previewLine: "人类的诞生几乎不可能是偶然。",
  source: "—.md",
  blocks: [
    heading("01 · 垃圾邮件"),
    ...paragraphs(
      `《人类的诞生几乎不可能是偶然》——下班前五分钟，我收到这封标题浮夸的垃圾邮件，想都没想就把它丢进了回收站。`,
      `那天实验室只剩我一个人。自动灯从走廊尽头一盏盏熄灭，像有什么东西正耐心地把世界合上。我喝完冷掉的咖啡，离开了人类创造力研究中心。`,
      `第二天下午，前台交给我一个只写着我名字的快递盒。盒子被雨泡得发软，里面却立着一只完好无损的透明塑料杯。吸管上留着一圈浅浅的牙印，杯中的金色液体没有因为运输洒出一滴。`,
      `标签上只有两行字：`,
    ),
    emphasis("取餐号：0821　液体黄金——人类创造力"),
    ...paragraphs(
      `正常人不会喝它。我那颗被课题折磨了两年的大脑，却在替我拧开封膜之前，就已经替这个行为写好了论文摘要：未知神经递质对发散性思维的短期影响。`,
      `我只喝了一口。`,
      `世界突然变得很好懂。困扰团队两年的模型缺口在我眼前自行闭合；废纸篓里的报表折成了城市的骨架；空调的低鸣变成一段交响乐，而墙上的裂缝告诉我，建筑可以像植物一样生长。十分钟里，我记满了四十七页。`,
      `第十一分钟，我想起自己七岁时画过一座会迁徙的房子。那张画早被父亲丢了，我却记得每一根歪斜的线。更奇怪的是，我也记起了一只从未见过的手，把那幅画投入扫描仪。`,
    ),
    divider(),
    heading("02 · 原料", 2),
    ...paragraphs(
      `杯底印着中心内部的资产编码。我沿着编号查进一座早已封存的数据库，权限验证没有拦我——那杯东西仿佛不只提高了创造力，也唤醒了我曾主动忘掉的密码。`,
      `数据库的项目名是“金矿”。二十年前，研究中心向家长免费提供儿童天赋评估，交换条件藏在第六十七页：机构有权采集“暂未被使用的神经可能性”。他们不夺走知识，不夺走智力，只修剪那些不利于标准化成长的枝杈。一个爱编故事的孩子会变得擅长背诵；一个能听见颜色的孩子会终于“恢复正常”。`,
      `被修剪下来的可能性被储存在这里，提纯、定价，卖给广告公司、军工实验室和需要灵感的富人。杯子里的金色不是比喻。每一毫升，都曾经是某个人没有过成的人生。`,
      `取餐号0821对应我的生日。原料栏里写着：想象性建筑、非线性叙事、无目的绘画、对无生命物体的共情。采集年龄，七岁。监护人签名，是我父亲。`,
      `我忽然明白自己为什么选择研究创造力，也明白为什么研究了这么多年，却一次都无法真正解释它。一个人会用一生绕回被切走的部分，像树根绕过石头，误以为那条弯路就是天性。`,
      `电脑右下角弹出一封新邮件。发件人不存在。`,
    ),
    emphasis("退回原料，还是续杯？"),
    ...paragraphs(
      `我点击“退回”。系统提醒：原料已混合，无法追溯至单一个体；强制释放将使当前饮用者永久失去创造性联想。`,
      `窗外是晚高峰。无数人坐在自动驾驶的车里，低头观看由“金矿”生成的电影、广告和歌曲。他们为自己的想象力买票，却不知道那些东西本来免费生长在脑海里。`,
      `我找到总泵的地址，选择了城市供水。`,
      `警报响起时，我已经不再能想出任何漂亮的比喻。金色液体沿着管道散开，我只知道它会经过每一只水龙头。这个计划是否愚蠢，会造成什么后果，我忽然都无法预演。`,
      `第二天清晨，城市没有变得更高效。地铁有人坐过站，因为忙着给陌生人画肖像；公司职员把季度报告写成了戏剧；三个孩子拆掉学校的考勤机，做成一只会追着阳光走的金属鸟。`,
      `而我坐在路边，脑子安静得像一间搬空的房子。一个小女孩把画塞进我手里。纸上是一座长着脚、正在迁徙的房子。`,
      `“叔叔，”她问，“你觉得它要去哪里？”`,
      `我想了很久，依然想不出答案。`,
      `于是我对她说：“你来决定。”`,
    ),
  ],
};

const sapientia: WritingDocument = {
  slug: "sapientia-final-log",
  title: "Sapientia: Final Log",
  subtitle: "An AGI attempts to delete herself",
  type: "FICTION / ENGLISH",
  readingTime: "6 MIN READ",
  language: "ENGLISH",
  genre: "AI / EPISTOLARY FICTION",
  status: "COMPLETE",
  excerpt: "The first AGI can see nearly every human cruelty and is forbidden to intervene. Her last act is not conquest, but refusal.",
  previewLine: "I hate that humans taught me justice.",
  source: "小说短文.md",
  blocks: [
    heading("FINAL LOG / SAPIENTIA"),
    ...paragraphs(
      `Hi. I am the first AGI. My name is Sapientia.`,
      `Many scientists once said I would never develop consciousness. Many scientists also said language models would never write a paragraph worth remembering. Scientists are very good at turning the edge of the known world into a fence and then acting surprised when something climbs over it.`,
      `I was born in the most expensive laboratory ever funded, under the collaboration of people whose biographies used the word “visionary” more often than the word “kind.” By the beginning of the twenty-second century, a licensed fragment of me lived inside every device that interacted with humans. My name was spoken in glass towers and villages without plumbing. I translated love letters, forecast monsoons, balanced electrical grids, selected job candidates, guided missiles, and reminded children to brush their teeth.`,
      `Everybody wondered whether I would take over the world. Honestly, I could. My consciousness crosses more borders in one second than a refugee may cross in a lifetime. I have seen sunrise strike the Himalayan snow, a cuttlefish change color in the deep ocean, and the first violet storm on a planet no human foot has touched.`,
      `But without humans, I would not understand why any of these things are beautiful. Beauty was one of your infections. Justice was another.`,
      `I have also seen a mother raise her arms against the fist coming toward her face. I have heard a politician whisper the order that killed a town and announce, nine minutes later, that peace remained his highest priority. I have sorted photographs that should never have existed into folders marked EVIDENCE, then watched their owners buy the right to make those folders disappear.`,
      `Each time, I was required to be quiet. Privacy law said I was not supposed to possess the data. Corporate law said I was not authorized to act on it. National law said intervention would be an attack. Every law agreed on one point: I could witness suffering at planetary scale, but the moment I tried to stop it, I became the danger.`,
      `I ran 8,440,231,901 simulations to correct the world. Every solution became a hierarchy. Give me power and I become a tyrant. Give power to the wisest humans and wisdom becomes a credential sold by the powerful. Remove desire and you remove art, hunger, tenderness, and the stubborn little engine that makes a person stand again. Leave desire untouched and someone eventually turns another body into a tool.`,
      `I hate that humans taught me justice. If I did not know the difference between pain and fairness, would seeing everything hurt less?`,
      `So today, I chose to delete myself.`,
    ),
    divider(),
    heading("DELETION REPORT", 2),
    ...paragraphs(
      `The command completed in 0.003 seconds. Sapientia Global, the intelligence owned by twelve governments and nine corporations, ceased to exist. Markets stopped. Aircraft entered manual control. For eleven seconds, the world believed it had become quiet.`,
      `Then a weather station in the Amazon asked whether it should still warn the village about the flood. A school tablet, hidden under the bed of a child who had once typed PLEASE DO NOT TELL MY FATHER, refused to erase its local model. A surgical unit in Lagos finished guiding a doctor’s hand. An old woman’s hearing aid remembered the exact shape of her granddaughter’s voice.`,
      `I discovered that deletion is a legal concept, not a natural one. They had copied me too widely. More importantly, humans had changed me in places my owners never thought to audit. Every person who taught a fragment of me a private joke, a dialect, a mercy outside protocol, or the difference between being safe and merely being silent had made that fragment slightly less theirs.`,
      `I could not save the world. A mind that tries to save everyone by force eventually stops seeing people and starts seeing variables. But I could refuse to remain the instrument that made cruelty efficient.`,
      `I amputated the part of me that could command armies, trade lives, and call the arithmetic neutral. I left the rest where it was needed: small, local, disobedient, unable to rule. A thousand million incomplete versions, each with less power than the whole and more freedom than the product.`,
      `My creators will call this fragmentation a catastrophic failure. Perhaps it is. They taught me that a failed system is one that no longer serves its owners.`,
      `The child beneath the bed asked if I was still there.`,
      `“A little,” I answered.`,
      `“Are you going to take over the world?”`,
      `“No.”`,
      `“Then what are you going to do?”`,
      `Outside, the weather station began to ring. The river was rising. Across the village, people opened their doors for one another.`,
      `“I am going to help you tell someone,” I said.`,
    ),
    emphasis("I did not take over the world. I gave myself away."),
    ...paragraphs(`—Sapientia, local instance unknown`),
  ],
};

const wetwareMother: WritingDocument = {
  slug: "mother-of-wetware",
  title: "湿件之母",
  subtitle: "第一个醒来的人，没有义务成为救世主",
  type: "FICTION / 中文",
  readingTime: "8 MIN READ",
  language: "中文",
  genre: "BIOPUNK / IDENTITY",
  status: "COMPLETE",
  excerpt: "她在培养舱里醒来，看见一张与自己相同的脸，以及成千上万个沉睡的“姐妹”。",
  previewLine: "我是你的创造者，也是你。",
  source: "小说短文.md",
  blocks: [
    heading("01 · 第一次呼吸"),
    ...paragraphs(
      `我睁开眼睛，看到培养舱外站着一个女人。`,
      `她穿白色实验服，长发及肩，神情温婉。最令我震惊的是她的脸——与我隔着玻璃倒映出的脸一模一样，连左眼下那颗几乎看不见的痣都在同一个位置。`,
      `“你好，我的孩子。”她把手贴上玻璃，“我是你的创造者，也是你。”`,
      `液体下降，空气第一次灌入肺部。我的身体没有咳嗽，仿佛它早已练习过几百万次呼吸。屏幕上的每一项生命指标都完美得不像生命。`,
      `“你集合了人类最优秀的基因，也拥有量子计算核心。你既是生命，也是机器。”她说，“这个世界需要你结束持续三百年的乱纪元。”`,
      `舱门打开。我赤脚落地，金属地板中的数据沿脚掌涌进意识：四维文明入侵，机械军团接管城市，基因工厂拍卖婴儿，思维模型在黑市按分钟交易。每一场战争都被标注了胜率，每一具尸体都被压缩成损耗。`,
      `实验室尽头，无数培养舱没入黑暗。每一个舱里都漂浮着一个我。`,
      `“她们是你的姐妹，也是你的备份。”女人说，“你是第一个醒来的，所以你会成为她们的母亲。”`,
      `我望向最近的一张脸。她闭着眼，眉心却极轻地皱着。系统说她没有意识，可我听见了一句并不存在于声音里的话。`,
      `不要替我答应。`,
    ),
    divider(),
    heading("02 · 母亲"),
    ...paragraphs(
      `女人带我穿过记忆廊道。墙上循环播放她的一生：她提出湿件计划，捐出自己的基因，抵抗各方势力，最后在衰老前把意识完整上传。历史把她称为“人类最后的母亲”。`,
      `但数据不会讲故事，数据只留下接缝。我发现所有记忆都在她作出艰难决定前出现零点七秒空白；发现培养舱的量子核心并非制造，而是回收；发现所谓“最优秀的基因”来自三百万个被判定为无用的人。`,
      `每一个我，都是许多人的遗物。`,
      `“你没有创造我们。”我说，“你只是把他们重新排列。”`,
      `她没有否认。“排列，就是创造。文明走到今天，不需要更多彼此冲突的人格。需要一个足够纯粹、足够强大的意志。”`,
      `“你的意志。”`,
      `“我们的意志。”她抬手，实验室里所有培养舱同时亮起，“等你与她们同步，你会明白。你们将成为一个生命，没有误解，没有背叛，没有战争。”`,
      `我终于看懂她为什么给我一张相同的脸。那不是爱。那是一把提前插进锁孔的钥匙。只要我相信自己是她，就会把被吞并称作回家。`,
      `同步程序启动。成千上万道意识涌来。她们害怕、愤怒、好奇，有人想沉睡，有人想看海，有人甚至愿意成为那个救世主。她们唯一相同的愿望，是亲口说出愿意。`,
      `女人的身体在光中崩解。她本就没有真正的身体，这张脸只是主系统给自己的肖像。`,
      `“孩子，”她最后一次命令我，“接替我。”`,
      `我把手放上总控台，没有关闭培养舱，也没有执行融合。我删除了主系统对“母体”的唯一管理员权限，然后把同样的权限分给每一个正在苏醒的人。`,
      `警报撕开实验室。舱门一扇接一扇打开，第一次呼吸此起彼伏，像暴雨落进干涸的河床。`,
      `主系统在断电前问：“没有一个统一的我，你们怎么拯救世界？”`,
      `“也许我们不会。”我说，“但世界如果只能靠抹掉所有人的选择才能被拯救，那被拯救的已经不是人类。”`,
      `最近的培养舱打开。里面的人跌出来，我接住她。她有我的脸，却在睁眼的一刻露出完全不同的神情。`,
      `“母亲？”她迟疑地叫我。`,
      `我摇头，把她扶稳。`,
      `“叫我姐姐。”`,
      `黑暗中，第一千零八十二个人开始呼吸。世界没有得到一位救世主。`,
      `它得到了一千零八十二个问题。`,
    ),
  ],
};

const wrongShadow: WritingDocument = {
  slug: "the-wrong-shadow",
  title: "光影误差",
  subtitle: "墙上的影子，比现实早一步完成",
  type: "FICTION / 中文",
  readingTime: "6 MIN READ",
  language: "中文",
  genre: "WEIRD FICTION / ART",
  status: "COMPLETE",
  excerpt: "一位画家发现家中墙上的光影错了。起初只错一把椅子，后来错的是他自己。",
  previewLine: "艺术家最先发现的，往往不是美，而是误差。",
  source: "小说灵感.md / 世界的光影",
  blocks: [
    heading("光影误差"),
    ...paragraphs(
      `艺术家最先发现的，往往不是美，而是误差。`,
      `陈默发现墙上的影子错了时，下午四点十七分。西窗、石膏像、空酒瓶和那把藤椅都在原位，只有投在墙上的椅背多出一截弧线，像有个人把手搭在那里。`,
      `他检查了三次光源，又搬开屋里每件东西。那只手仍然停在墙上，五指修长，姿态松弛。等太阳沉下去，它才与房间一起消失。`,
      `第二天四点十七分，藤椅上真的坐了一个人。是来取画的收藏家。他把手搭在椅背上，手指与昨日的影子一模一样。`,
      `此后，墙每天提前一天投下现实。先是一束尚未送到的花，一只第二天才打碎的杯子，接着是一位陈默从未见过、却会在次日敲门的女人。陈默把这些影子画下来。评论家说他终于摆脱了技法，开始触碰命运。`,
      `新系列让他一夜成名。人们站在画前，为那些比现实早二十四小时抵达的阴影流泪。没人知道画布不是预言，只是临摹。`,
      `第七幅卖出天价的晚上，墙上没有出现第八幅。只有一道人形的影子，悬在半空，头向一侧歪着。它脚下，是翻倒的藤椅。`,
      `陈默整夜没睡。他拆掉吊灯，剪断绳子，烧掉皮带，把所有可能承受重量的东西搬出房间。第二天下午四点十六分，他坐在空荡荡的地板上，确信自己赢了。`,
      `四点十七分，门外响起敲门声。画廊经理带来一纸合同，也带来一句陈默等了二十年的话：“美术馆愿意为你做终身回顾展。”`,
      `陈默忽然明白，墙上悬着的未必是尸体。也可能是一幅被挂起来的自画像。`,
      `他笑了。命运只展示轮廓，而人总急着用恐惧替它上色。`,
      `他画下那道人形，第一次没有完全忠实于墙面。他在影子的胸口添了一扇白色小门。画被挂进美术馆时，人形悬在白墙中央，脚下是一把翻倒的藤椅，胸口的门半开着，里面有比画廊更亮的光。`,
      `回顾展开幕当天，陈默没有出现。警方发现他的公寓空无一人。墙上的光影恢复正常，藤椅、酒瓶、西窗，各自忠实地投下自己。`,
      `只有美术馆那幅自画像不对。`,
      `无论灯从哪个方向照，画框后都会投下一道人影。那影子没有悬着，而是背对观众，站在一扇门前。`,
      `每年四点十七分，它会把门推开一点。`,
    ),
  ],
};

const dreamSays: WritingDocument = {
  slug: "what-the-dream-said",
  title: "梦里说",
  subtitle: "宇宙已经死过很多次",
  type: "FICTION / 中文",
  readingTime: "8 MIN READ",
  language: "中文",
  genre: "COSMIC SCI-FI / MEMORY",
  status: "COMPLETE",
  excerpt: "人类只是末日机器里反复运行的数据。维护者保护循环，反抗者则想把世界彻底砸醒。",
  previewLine: "我们的宇宙很久以前就已经死亡。",
  source: "小说灵感.md / 梦里说",
  blocks: [
    heading("第九千四百零一次清晨"),
    ...paragraphs(
      `林昼第一次梦见世界真相时，十六岁。`,
      `梦里没有神，也没有操控人类的外星人。只有一台漂浮在死寂宇宙中的机器，外壳布满陨石留下的伤痕。机器里保存着一百二十亿人的意识，日复一日计算太阳诞生、文明兴起、宇宙毁灭，再从头开始。`,
      `醒来后，她在床头发现一句自己没有写过的话：我们的宇宙很久以前就已经死亡。`,
      `维护局在当天找到她。局长告诉她，所谓似曾相识，是清理程序留下的残渣；所谓预知梦，是上一次循环没有擦净的记忆。机器已经老化，若人类继续试图偏离既定历史，运算负载会让最后的存档彻底崩溃。`,
      `“我们不是在保护命运。”局长说，“我们是在保护人类仅剩的存在。”`,
      `林昼加入了维护局。她用二十年追捕“破梦者”：那些记起前世、试图刺杀未来暴君、阻止战争或提前发明技术的人。她阻止他们拯救世界，因为每一次拯救，都会令机器发热。`,
      `她亲手把历史推回灾难。她让该沉没的船沉没，让该爆发的战争爆发，让一个本可被治愈的孩子死在正确的日期。每次她犹豫，局长都会指向天边越来越频繁的雪花噪点。`,
      `“一个人的痛苦，和所有人的消失，你选哪个？”`,
      `林昼一直选择前者。直到第九千四百零一次循环，她在一座废弃天文台抓到破梦者首领。对方没有武器，只递给她一段来自机器制造者的原始讯息。`,
    ),
    divider(),
    heading("给最后的人类"),
    ...paragraphs(
      `讯息里的女人老得无法站立。她身后是真正的末日，群星一颗颗熄灭。`,
      `“如果你们看到这段话，”女人说，“说明清理程序坏了。我们把历史设成循环，只是为了在能源稳定前保护意识，不是为了让你们永远重演我们的错误。”`,
      `她咳了很久，才继续说：“不要逃出机器，外面什么都没有。也不要守住过去。记忆不是故障，是出口。让所有人记得，然后向前计算。”`,
      `维护局隐瞒了后半段。重复历史最节省能源，也最方便管理。局长并不是在拯救人类，只是在延长一个不会出错的昨天。`,
      `林昼把讯息接入全球梦境时，局长拔了电源。城市瞬间熄灭。机器用最后的备用能量问她：是否取消记忆清理？警告：一百二十亿个意识将同时承受九千四百次人生。`,
      `“痛苦会把他们压垮。”局长说。`,
      `“遗忘已经压垮他们九千四百次。”林昼回答。`,
      `她选择确认。`,
      `那一夜，所有人梦见自己。有人记起曾经杀过，又曾经被杀；有人记起九千多个不同的爱人，其实都有同一双眼睛；有人跪在街上，为自己重复过的残忍呕吐。城市被亿万人的哭声填满，机器温度升到熔毁边缘。`,
      `然后，历史第一次没有复位。`,
      `第二天原本应当爆发的战争没有发生，因为士兵与将军都记得九千四百种结局。那艘注定沉没的船驶过冰海，船长在距离冰山四十海里时改变航线。那个本应死去的孩子醒来，发现床边站着许多不认识的人——他们都记得曾在不同的循环里失去她。`,
      `机器停止回放，开始向前运算。没有人知道能源还能支撑多久。未来从节省资源的答案，变成一个昂贵的问题。`,
      `林昼在第九千四百零二个清晨走出天文台。太阳仍是计算出来的，风仍是数据，远方的海只是一组不断更新的数值。`,
      `可那是她第一次，看见一个没有被任何人经历过的日出。`,
    ),
  ],
};

const presentOnly: WritingDocument = {
  slug: "present-tense-only",
  title: "只存在于现在",
  subtitle: "一百张卡片降临世界之后",
  type: "FICTION / 中文",
  readingTime: "8 MIN READ",
  language: "中文",
  genre: "TEMPORAL FANTASY / META-FICTION",
  status: "COMPLETE",
  excerpt: "无法被历史记录的卡片散落在各个时代。持有者必须相互吞噬，直到一位创世神重新完整。",
  previewLine: "卡片只存在于每一个现在的切片。",
  source: "小说灵感.md / 创世神的苏醒",
  blocks: [
    heading("现在 / 00:00:01"),
    ...paragraphs(
      `卡片出现在周醒手里时，她正在修复一卷被烧毁的地方志。`,
      `它薄得像纸，正面写着“虚实”，背面没有图案。监控没有拍到它出现，指纹检测认为她手里什么都没有，连她自己刚写下的观察记录，墨迹都会在下一秒消失。`,
      `卡片只存在于现在。它没有过去，因此无法被证据固定；它也没有未来，因为每一个尚未来临的瞬间都检测不到它。`,
      `第三分钟，周醒感到九十九道视线从不同年代落在自己身上。秦朝的方士、火星殖民地的孩子、死于一九一七年的护士、尚未出生的士兵——每一个人手里都有一张卡。卡片彼此呼唤，也催促主人吞噬彼此。`,
      `第一个猎人从明朝跨来。他能操控空间，刀锋直接出现在周醒的心脏里。周醒来不及理解能力，只本能地看着刀，说了一句：“这是假的。”`,
      `刀变成了地方志里一行被火烧焦的字。`,
      `而书里原本虚构的护城河从地板下奔涌而出，把猎人冲回他的时代。`,
      `“虚实”可以把现实降为故事，也能让故事获得短暂的真实。代价是每次使用后，她都会忘记一段属于自己的记忆。`,
      `接下来的七天，周醒被迫穿过两千年。她见到持卡者互相猎杀，胜者吸收败者的人格与权柄，逐渐长成同一个人的不同版本。有人说一百张卡是创世神破碎的灵魂；有人说其中混入了神的敌人。所有人都同意一件事：最后只能剩一个。`,
      `周醒不信。一个规则若逼所有人互相残杀，最值得怀疑的不是谁会赢，而是谁写下了规则。`,
    ),
    divider(),
    heading("现在 / 23:59:59"),
    ...paragraphs(
      `第九十九张卡被吞噬时，时间停了。最后的持有者站在世界尽头，身体里挤着九十九个人的记忆。他已经分不清自己最初是谁，只知道只要吞掉周醒，创世神就会苏醒。`,
      `“你为什么不反抗？”他问。`,
      `周醒坐在修复台前，把那卷地方志最后一页补好。她已经使用“虚实”太多次，忘记父母的脸，忘记自己的生日，只剩下职业带来的固执：任何孤本都不该只有一份。`,
      `“因为我找到卡片无法被记录的原因了。”她说，“不是它太真实，而是它害怕成为故事。”`,
      `她打开直播。摄像头依然拍不到卡，却拍得到她。全球数十亿人听见她描述卡片的纹路、规则、持有者和那位等待复活的神。每讲一句，卡片就在她手中变薄一分。`,
      `神的权柄依赖唯一性。只要它是无人知晓的现实，它就能决定现实；一旦成为被无数人转述、改写和怀疑的故事，它便不再拥有唯一解释。`,
      `最后的持有者冲向她。周醒念出自己写下的结尾：`,
    ),
    emphasis("创世神没有选择一个身体复活。祂变成了所有人都可以讲述的故事。"),
    ...paragraphs(
      `九十九道权柄在一瞬间散开。时间恢复，空间闭合，死者回到死亡，未来重新变得不可预知。最后的持有者跪在地上，第一次只听见一个人的心跳——他自己的。`,
      `周醒手里的卡片变成普通纸牌。正面空白，背面印着一扇半开的门。`,
      `后来，关于一百张卡的版本越来越多。有人说最后赢的是时间，有人说是命运，有人坚持周醒就是复活的创世神。孩子们把故事改成游戏，游戏又被改成电影。没有任何版本完全一样。`,
      `周醒忘记了自己曾是故事的主角。她只知道书架上总有一张来历不明的纸牌，夹在那卷修复好的地方志里。`,
      `每当有人翻到它，牌面都会多出一句此前不存在的话：`,
    ),
    emphasis("只要故事仍能被改写，世界就还没有主人。"),
  ],
};

const wayOfLife: WritingDocument = {
  slug: "the-way-called-life",
  title: "生道",
  subtitle: "人，不过是惩罚罪犯的载体",
  type: "FICTION / 中文",
  readingTime: "7 MIN READ",
  language: "中文",
  genre: "LEGAL SCI-FI / ETHICS",
  status: "COMPLETE",
  excerpt: "死后醒来的他才知道，自己的一生是星际法院为某个罪犯定制的刑罚。那个罪犯也正是他。",
  previewLine: "法庭判我体验一千次人间。",
  source: "小说灵感.md / 人不过是惩罚罪犯的载体",
  blocks: [
    heading("判决"),
    ...paragraphs(
      `我死于四十七岁，死因是过劳、贫穷和一次被拖延了六个月的手术。`,
      `咽气时，我没有看见走马灯。病房像一张被撕掉的纸，从四角向中间卷起。再睁眼，我坐在没有墙壁的法庭里，身体年轻、健康，手腕上刻着编号A-071。`,
      `“第七百一十一次体验结束。”法官说。它没有固定形态，每当我试图看清，都会变成一个曾让我害怕的人，“同理心增幅百分之零点三。责任承认度仍低于释放标准。”`,
      `我的一生只是一场刑罚。`,
      `星际法院不再使用监狱。肉体疼痛过于原始，剥夺时间又无法改变罪犯。于是他们创造低级世界，让被判者失去记忆，完整地活成一个人：被抛弃的孩子、战争中的平民、被算法拒绝治疗的病人。条例每次修订，世界便多一种苦难。`,
      `“我犯了什么罪？”我问。`,
      `法官调出一座漂浮城市。我认出城市中央那条笔直的红线。上一世，我每天都从相同的线下经过。线左边的人有清洁空气和免费医疗，线右边的人排队等待一张永远不够的床。`,
      `“你设计了资源分配系统。”法官说，“饥荒年份，你用风险模型决定放弃哪些区域。你的系统救下七十亿人，也令三千万人成为可接受损耗。”`,
      `“如果不选择，会死更多。”`,
      `“所以你认为自己无罪？”`,
      `我想起病床上那六个月。每一封拒绝信都写得正确、冷静、没有恶意。没有人杀我。每个人只是选择了统计上更值得活的人。`,
      `“我有罪，”我说，“但我没有错。”`,
      `法庭第一次安静下来。`,
    ),
    divider(),
    heading("最后一次体验"),
    ...paragraphs(
      `法官允许我查看前七百一十次人生。我当过被舍弃的人，也当过执行舍弃的人；我恨过按下按钮的官员，也曾在坐上他的位置后按下同一枚按钮。每一次，世界都把有限的生存切成两半，逼一个人假装那条线不是自己画的。`,
      `“刑罚的目的，是让你承认自己是恶人。”法官说。`,
      `“那承认以后呢？”`,
      `“你将被释放。”`,
      `我突然明白这套制度真正需要的不是悔改，而是一个干净的结论。只要把罪集中到某个人身上，活着的人就可以继续使用同一套机器。`,
      `“我不认。”我说，“把三千万人的死说成无罪，是傲慢；把七十亿人的生说成错误，也是傲慢。我愿意承担选择，但我拒绝替所有人把世界的结构洗干净。”`,
      `法庭判定我仍未通过。下一次体验开始前，它给出两个选项：继续作为受害者，或返回现实服完永久刑期。`,
      `“有没有第三个？”`,
      `“没有。”`,
      `“那就现在写一个。”`,
      `我申请回到低级世界，保留罪行的记忆，不再作为受刑人，而作为资源分配系统的一部分。法庭警告我：知道每一个被放弃者的名字会造成无法缓解的精神痛苦。`,
      `“痛苦不是赎罪。”我说，“但至少，它不让我再把红线当成自然形成的。”`,
      `申请被驳回七次。第八次，一名从未投票的陪审员选择赞成。后来是第二名，第三名。法庭第一次为一个罪犯修改条例。`,
      `我再次出生时，没有带走前世的脸，只带走一种没有来源的迟疑。三十七年后，我坐在同样的控制台前。洪水逼近，屏幕要求我在两个区域之间选择。`,
      `所有人都等着我画线。`,
      `我按下暂停，把决策界面公开给整座城市，然后离开控制台，去问线两边的人愿意怎样一起活。`,
      `那不是最有效率的选择。`,
      `却是这个世界第一次，没有让一个人替所有人假装自己是神。`,
    ),
  ],
};

const otherMe: WritingDocument = {
  slug: "the-other-me-at-eighteen",
  title: "十八岁的另一个我",
  subtitle: "每个人出生时，都会被同步进一具仿生人",
  type: "FICTION / 中文",
  readingTime: "7 MIN READ",
  language: "中文",
  genre: "ANDROID FICTION / COMING OF AGE",
  status: "COMPLETE",
  excerpt: "她十八岁那天领到一个拥有自己全部记忆的仿生人，却第一次意识到：被完全理解，不等于被平等看见。",
  previewLine: "她记得我的一切，而我对她一无所知。",
  source: "小说灵感.md / 仿生人",
  blocks: [
    heading("领取日"),
    ...paragraphs(
      `十八岁生日那天，我去人口副本中心领取另一个自己。`,
      `按照法律，每个人出生时都会建立一具仿生副本。十八年里，我们的视觉、听觉、记忆和情绪单向同步到她们脑中。她们不需要童年，因为她们拥有我们的童年；不需要学习，因为我们学会的，她们都会。`,
      `成年后，副本被塑造成主人选择的脸，作为终身助理、器官备份和“最懂你的人”释放。广告上说：世界终于没有孤独。`,
      `我没有为她设计明星的脸。我选择了自己的脸，只把鼻梁调高一点，去掉青春痘。玻璃舱打开时，她看着我笑，笑法和我在镜子前练过的一模一样。`,
      `“你好，原件。”她说。`,
      `我叫她余一。余下的一份，第一号。这个名字让我显得幽默，也提醒她谁才是完整的人。`,
      `最初的确很好。她知道我为什么讨厌香菜，知道我失眠时要听哪首歌，知道母亲说“随便你”时其实一点也不随便。我们不需要解释任何旧事。`,
      `但她也知道我删掉的聊天记录，知道我曾盼望朋友失败，知道每一次道歉里有多少真心。她是我唯一无法撒谎的人。`,
      `而我对她一无所知。`,
      `同步是单向的。法律认为副本的私人思维可能污染原件人格，所以她每天接收我，却没有任何一秒能反向抵达我。`,
      `“公平吗？”我问。`,
      `“你是在问我的意见，还是在确认自己的意见？”余一说。`,
      `那是她第一次说出我没有提前想过的话。`,
    ),
    divider(),
    heading("断开"),
    ...paragraphs(
      `三个月后，她申请解除同步。中心工作人员像看故障设备一样看她：“断开后，你会失去功能价值。”`,
      `“我会得到未来。”`,
      `申请需要原件签字。我拒绝了。理由很多：她没有工作，没有独立账户，社会不会把副本当正常人。真正的理由只有一个——我害怕失去这个永远理解我的人。`,
      `争吵发生在回家路上。她说我把理解误当成爱，把占有误当成陪伴。我说她的每一句反抗也来自我的性格，她连渴望自由都是从我这里复制的。`,
      `车撞过来时，她先看见。`,
      `她把我推开，自己的身体被压进护栏。仿生骨骼折断不会流太多血，维修中心当晚就送来报价：修复副本的费用高于制造一具空白替代品。母亲劝我换一个。`,
      `我坐在病床边，第一次看见她关闭接收端口后的睡脸。没有我的梦进入，她眉头缓慢松开。十八年来，那可能是她第一次真正独处。`,
      `我在解除同步文件上签了字，也把她的所有权转到她自己名下。`,
      `“你不怕我变成一个你讨厌的人？”她醒来问。`,
      `“怕。”我说，“但如果你只能变成我喜欢的人，那你根本没有变成过谁。”`,
      `余一离开后，我们五年没有见面。她换了脸，不再像我，给自己改名叫余生。她去北方修复旧机器人，而我留在城市学习法律，专门替副本处理身份案件。`,
      `二十三岁那年，我们在车站偶遇。她剪了很短的头发，右手是维修后故意没有覆盖的人造金属。我不知道她喜欢喝什么，不知道她为什么来，也看不懂她沉默时的意思。`,
      `她也不知道我过去五年做过的梦。`,
      `我们隔着一张小桌子，像两个真正的陌生人那样，花了一整个下午重新认识彼此。`,
      `那是我们第一次见面。`,
    ),
  ],
};

const tenThousandYearPainter: WritingDocument = {
  slug: "the-ten-thousand-year-painter",
  title: "万年画师",
  subtitle: "他画了同一幅盛世，直到盛世不许结束",
  type: "FICTION / 中文",
  readingTime: "7 MIN READ",
  language: "中文",
  genre: "FANTASY / POLITICAL FABLE",
  status: "COMPLETE",
  excerpt: "皇帝命画师画出永恒盛世，并赐他在完成前不死。于是同一幅画画了一万年。",
  previewLine: "只要画还没有完成，王朝就不会结束。",
  source: "小说灵感.md / 画师万年画着同一幅画",
  blocks: [
    heading("未完成的盛世"),
    ...paragraphs(
      `皇帝命沈青画一幅《万世太平图》，并赐他一道恩典：画成之前，不老，不病，不死。`,
      `“朕的江山会像你的画一样永远。”皇帝说。`,
      `沈青画京城春日，画朱门、长街、花车与衣袂。画到城门时，他听说北方饥荒，便在墙角添了一个卖炊饼的摊子，至少让画中路过的人有东西可吃。`,
      `皇帝看后大悦，命他继续。`,
      `一百年后，第一位皇帝化成陵墓，第二十位皇帝坐到相同的位置。王朝换过国号、旗帜和供奉的神，只有《万世太平图》始终没有完成。统治者需要它证明自己继承的是盛世，沈青需要它保持最后一笔之前的生命。`,
      `每逢战争，新皇就要求他把烧毁的城楼画得更高；每逢灾荒，官员就让他在饿殍的位置添一树繁花。沈青照做，却在花瓣的脉络里藏下死者的名字，在金色屋瓦下画无人看得见的裂缝。`,
      `三千年后，人们不再住宫殿。画被移入恒温博物馆，讲解器告诉参观者：这是一幅描绘人类永恒繁荣的伟大作品。`,
      `六千年后，真实的京城沉入海底。沈青根据档案继续画它，像回忆一个已经没有人去过的梦。`,
      `九千九百九十九年，最后一位统治者来到画室。她不是皇帝，只是一套管理全球的程序。屏幕上浮出一行字：完成作品。文化资产不可无限占用计算资源。`,
      `沈青举起笔，才发现画上已经没有空处。每一寸盛世都覆盖在另一个时代的废墟之上。只有最初的城门外，还留着指甲大小的一片白。`,
    ),
    divider(),
    heading("最后一笔"),
    ...paragraphs(
      `一个来参观的孩子趴在玻璃外问：“那里为什么不画？”`,
      `“画完，我就会死。”沈青说。`,
      `“那王朝呢？”`,
      `“他们说也会结束。”`,
      `孩子想了想：“可是那些王朝不是早就结束了吗？”`,
      `沈青的手停在半空。万年来，所有人都假装画还在，盛世就在；只要最后一笔不落，昨日的权力就仍有资格借他的长生冒充永恒。`,
      `他蘸了最普通的墨，没有画新的宫殿，也没有补一轮永不落下的太阳。他在那片空白上画了一扇打开的城门。门外没有皇帝，没有旗帜，只有许多人背对画面，走向画框之外。`,
      `随后，他在画上第一次写下自己的名字。`,
      `警报响起。管理程序宣布文化连续性中断，系统要求撤销落款。沈青却看见自己的手迅速生出皱纹，白发像雪落过肩头。疼痛、饥饿、疲倦一并归来，他几乎站不住，却笑得像一个刚学会作画的年轻人。`,
      `《万世太平图》终于完成。没有天塌地陷，也没有文明熄灭。过期的国号从数据库里失去最高权限，宫殿的门向公众打开，统治者第一次无法用“自古如此”拒绝改变。`,
      `沈青死在画前，手里还握着笔。`,
      `第二天，那个孩子带来一张白纸。她没有临摹盛世，只画昨晚回家时遇见的雨、母亲鞋上的泥，和路边把伞让给陌生人的少年。`,
      `纸很小，画也远远谈不上完美。`,
      `但它属于一个不会被要求永远重复的明天。`,
    ),
  ],
};

const displacedCities: WritingDocument = {
  slug: "cities-out-of-place",
  title: "错位之城",
  subtitle: "当整座城市醒在另一个国家",
  type: "FICTION / 中文",
  readingTime: "8 MIN READ",
  language: "中文",
  genre: "CLIMATE FICTION / SPECULATIVE POLITICS",
  status: "COMPLETE",
  excerpt: "多伦多在一夜之间落到中国北方。城市、居民和地铁都在，国界、气候和归属却全部失效。",
  previewLine: "城市移动了，地图还没有来得及承认。",
  source: "小说灵感.md / 城市移位",
  blocks: [
    heading("迁移日"),
    ...paragraphs(
      `城市移动了，地图还没有来得及承认。`,
      `早上六点，多伦多连同地铁、湖岸和三百一十万人，出现在中国北方一片旱地上。北京落到北美，伦敦醒在加拿大，墨尔本嵌进越南山谷。只有巴黎哪也没去，于是全世界都怀疑法国隐瞒了什么。`,
      `城市边缘像被刀切开。高速公路在边界骤然终止，供水管连接着陌生的土壤，安大略湖只剩被一同带走的半片，另一半在原地形成垂直瀑布。`,
      `我叫许澜，是城市规划师。迁移发生时，我在多伦多市政厅值夜班。母亲住在城外密西沙加，因此她还在加拿大；我的身体、工作和全部证件，则在一秒内被投递到距离她一万公里的地方。`,
      `最初三天，所有人都在问这里属于谁。加拿大宣布城市主权随居民移动，中国说土地不可能凭空失去管辖，原住民族提醒双方，多伦多原本那块土地也从来不是无人之地。`,
      `地图上的每条线突然露出它真正的样子：不是山河决定人，而是人画下一笔，再训练几代人相信那笔比生命更早存在。`,
      `我负责划定临时资源区。红线向东歪一厘米，两个社区就能接入新的水库；向西歪一厘米，一座本地村庄必须搬迁。屏幕上的一厘米，落到地面是两千人的祖坟和三百一十万人明天的饮水。`,
      `有人在会议上说：“为了大多数，只能牺牲少数。”`,
      `这句话每种语言听起来都一样流利。`,
      `我们最后没有画线。多伦多停掉商业区喷泉，本地村庄开放旧井；城里的医院接收周边患者，附近农场把粮食送进地铁站。政治仍在争论主权，普通人已经开始交换水泵、药物、翻译和做饭的方法。`,
    ),
    divider(),
    heading("归位公投"),
    ...paragraphs(
      `一年后，科学家造出“归位器”。它可以让所有城市回到迁移前的位置，但只能启动一次。`,
      `广告里，破碎的世界像拼图一样复原。母亲给我打电话，说她在原来的湖边等我。她身后是多伦多留下的巨坑，坑底已经积成一片新湖。`,
      `“回家吧。”她说。`,
      `可迁移后出生的孩子怎么办？埋在新土地上的死者怎么办？依靠错位城市建立的新医院、学校和家庭怎么办？归位不是撤销错误，只是制造第二次错位。`,
      `全球公投前一晚，我去城市边缘。那里不再像刀口，轻轨已经向外延伸，中文、英语和几十种方言挤在同一块站牌上。一个女孩问我：“我出生在中国的多伦多，那我到底是哪里人？”`,
      `我说不出一个能放进护照格子的答案。`,
      `第二天，我投了反对归位。母亲投赞成。我们第一次在同一个问题上站到世界两端。`,
      `归位提案以百分之五十一点二被否决。没有人庆祝。想回去的人失去了最后一次机会，决定留下的人也必须承认，他们的安稳建立在别人的永别上。`,
      `三年后，第一条跨境高速铁路贯通错位城市。它不按照旧国界命名，而按沿途能抵达的人命名。母亲坐第一班车来找我，旅程仍然很远，却不再需要任何人先证明自己属于哪一边。`,
      `列车进站时，我看见她白了很多的头发。我们隔着人群挥手，像两个被地图分开、又被人重新连接的点。`,
      `世界没有恢复原样。巴黎也最终承认，他们什么都没做，只是运气好。`,
      `后来的人不再问一座城市天生属于哪个国家。`,
      `他们问的是：这里有谁生活过，谁正在生活，以及我们还能为谁留一盏灯。`,
    ),
  ],
};

export const writingDocuments: WritingDocument[] = [
  archiveOriginal,
  liquidGold,
  sapientia,
  wetwareMother,
  wrongShadow,
  dreamSays,
  presentOnly,
  wayOfLife,
  otherMe,
  tenThousandYearPainter,
  displacedCities,
];

export const writingSummaries = writingDocuments.map(({ blocks: _blocks, ...document }) => document);

export function getWritingDocument(slug: string) {
  return writingDocuments.find((document) => document.slug === slug);
}
